version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Specify the version of Node.js you want to use
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
